export const Questions = [
    {
        prompt: 'Who i am ?',
        optionA : 'a) Tasim',
        optionB : 'b) Tanju',
        optionC : 'c) Tennur',
        optionD : 'd) Erdinch',
        answer  : 'B',
    },
    {
        prompt: 'What is a 9*9 ?',
        optionA : '78',
        optionB : '90',
        optionC : '81',
        optionD : '100',
        answer  : 'C',
    },
    {
        prompt: 'Who create a book Pod Igoto?',
        optionA : 'ME',
        optionB : 'You',
        optionC : 'Ivan Vazov',
        optionD : 'I dont know',
        answer  : 'C',
    },
    {
        prompt: 'Who create Tesle?',
        optionA : 'ME',
        optionB : 'Elon Musk',
        optionC : 'You',
        optionD : 'Johny Deep',
        answer  : 'B',
    },
    {
        prompt: 'Who is the best football player in the wolrd?',
        optionA : 'ME',
        optionB : 'You',
        optionC : 'Mesii',
        optionD : 'C.Ronaldo',
        answer  : 'C',
    },
    {
        prompt: 'Who create a book Pod Igoto?',
        optionA : 'ME',
        optionB : 'You',
        optionC : 'Ivan Vazov',
        optionD : 'I dont know',
        answer  : 'C',
    },
    {
        prompt: '`Who is the best programmer ever`?',
        optionA : 'Dennis Ritchie',
        optionB : 'Bjarne Stroustrup.',
        optionC : 'James Gosling',
        optionD : 'Me',
        answer  : 'D',
    },
]